openapi: 3.0.3
info:
  title: Prometheus API
  version: 1.0.0
paths:
  /stock/ohlc:
    get:
      operationId: stock_ohlc_retrieve
      tags:
      - stock
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses: {}
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
